FROM node:16-alpine3.16
WORKDIR /usr/farmhub
COPY package.json .
RUN npm install typescript yarn -g --force
RUN yarn install
COPY . .
RUN yarn prisma:migrate
# RUN yarn build
EXPOSE 8080
EXPOSE 5555
CMD ["yarn", "dev"]