version: '3.7'
services:
  postgres:
    image: postgres:14-alpine
    container_name: postgres
    ports:
      - "5432:5432"
    expose:
      - 5432
    restart: always
    networks:
      - postgres
    env_file:
      - .env
    volumes:
      - 'db:/var/lib/postgresql/data'

  api:
    build: .
    container_name: api
    restart: always
    networks:
      - postgres
      - traefik-public
    depends_on:
      - postgres
    ports:
      - '8080:8080'
    env_file:
      - .env
    volumes:
      - ./public:/usr/farmhub/public
    labels:
      traefik.enable: "true"
      traefik.http.routers.api-http.entrypoints: http
      traefik.http.routers.api-http.middlewares: https-redirect
      traefik.http.routers.api-http.rule: Host(`farmhub.devmoran.com`)
      traefik.http.routers.api-http.service: api
      traefik.http.routers.api-https.entrypoints: https
      traefik.http.routers.api-https.rule: Host(`farmhub.devmoran.com`)
      traefik.http.routers.api-https.service: api
      traefik.http.routers.api-https.tls: "true"
      traefik.http.routers.api-https.tls.certresolver: le
      traefik.http.services.api.loadbalancer.server.port: "8080"
      
        

volumes:
  db:

networks:
  postgres:
  traefik-public:
    external: true
