version: '3.7'
services:
  postgres:
    image: postgres:14-alpine
    container_name: db
    restart: always
    env_file:
      - .env
    volumes:
      - 'db:/var/lib/postgresql/data'

  api:
    build: .
    container_name: api
    restart: always
    depends_on:
      - postgres
    ports:
      - '8080:8080'
    env_file:
      - .env
    links:
      - postgres

volumes:
  db: